---
- name: Setup New Raspberry Pi
  hosts: all
  vars_prompt:
  - name: new_user_username
    prompt: Enter new user's Username (this will replace the default 'pi' user)
    private: false

  - name: new_user_password
    prompt: Enter new user's Password
    private: true
    encrypt: sha512_crypt
    confirm: true
    salt_size: 7

  - name: lan_ssid
    prompt: Enter ssid of lan wifi (the ssid the pi hosts for devices to connect to)
    private: false

  - name: lan_pass_phrase
    prompt: Enter the passphrase of the lan wifi (Passphrase you will use to connect TO THE raspberry pi)
    private: true
    confirm: true
  become: true
  tasks:
    - name: Ensure intial setup is run
      ansible.builtin.include_role:
        name: ../roles/inital_setup

    - name: Ensure ssh hardening is run
      ansible.builtin.include_role:
        name: ssh_hardening

    - name: Ensure lan_interfaces is run
      ansible.builtin.include_role:
        name: lan_interfaces

    - name: Ensure default pi user is removed
      ansible.builtin.include_role:
        name: remove_default_user
      become: true
      become_method: su
      become_user: {{ new_user_username }}
      vars:
        ansible_become_pass: "{{ new_user_password }}"
